article_index:
    path: /article
    controller: 'App\Controller\ArticleController::index'

article_create:
    path: /article/create
    controller: 'App\Controller\ArticleController::create'

article_save:
    path: /article/save
    controller: 'App\Controller\ArticleController::save'

article_show:
    path: /article/{id}
    controller: 'App\Controller\ArticleController::show'

article_edit:
    path: /article/{id}/edit
    controller: 'App\Controller\ArticleController::edit'

article_delete:
    path: /article/{id}/delete
    controller: 'App\Controller\ArticleController::delete'

grade_showFunctions:
    path: /grade/showFunctions
    controller: 'App\Controller\GradeController::showFunctions'

grade_cloneObjects:
    path: /grade/cloneObjects
    controller: 'App\Controller\GradeController::cloneObjects'
